
export const GETERROR = "GETERROR";
export const GETLISTVOCA = "GETLISTVOCA";
export const GETLIST_CONTENTSTORY = "GETLIST_CONTENTSTORY";
export const GETLIST_CONTENTSTORYTEXTBOX = "GETLIST_CONTENTSTORYTEXTBOX";